version = 1

exclude_patterns = [
  "bin/**",
  "**/node_modules/",
  "js/*/*.min.js"
]

test_patterns = [
  "tests/**",
  "test_*.py"
]

[[analyzers]]
name = "test-coverage"
enabled = true

name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"
