language: python
python:
- '3.7'
install:
- pip install -r requirements.txt
script:
- pytest

after_success:
  # Generate coverage report in xml format
  - coverage xml
   
  # Install deepsource CLI
  - curl https://deepsource.io/cli | sh
   
  # From the root directory, run the report coverage command
  - ./bin/deepsource report --analyzer test-coverage --key python --value-file ./coverage.xml
#