Application:
  type: "object"
  properties:
    id:
      type: "string"
      format: "uuid"
      example: "0422af6-64b3-4625-bea7-3942cf760681"
    interest_statement:
      type: "string"
      example: "I am interested in this opportunity because..."
    interview_date:
      type: "string"
      format: "date"
      example: "2020-03-21"
    interview_time:
      type: "string"
      example: "13:00:00"
    interview_completed:
      type: "boolean"
      default: false
    status:
      type: "string"
      description: "Application Status"
      enum:
        - "draft"
        - "submitted"
        - "recommended"
        - "interviewed"
        - "considered_for_role"
    is_active:
      type: "boolean"
      default: true
    contact:
      $ref: "./contact.yaml#Contact"
  xml:
    name: "Order"
