from flask import Blueprint
from flask_restful import Api

from app import resources

api_bp = Blueprint('api', __name__)
api = Api(api_bp)

# Route
api.add_resource(resources.ContactAll,
                 '/contacts/',
                 '/contacts',
                 '/')
api.add_resource(resources.ContactOne,
                 '/contacts/<int:contact_id>',
                 '/contacts/<int:contact_id>/')
api.add_resource(resources.ContactAccount,
                 '/contacts/me',
                 '/contacts/me/')
api.add_resource(resources.ContactShort,
                 '/contacts/short',
                 '/contacts/short/',
                 '/contacts',
                 '/contacts/')
api.add_resource(resources.ContactApproveMany,
                 '/contacts/approve',
                 '/contacts/approve/')
api.add_resource(resources.ContactSkills,
                 '/contacts/<int:contact_id>/skills',
                 '/contacts/<int:contact_id>/skills/')
api.add_resource(resources.ContactSkillOne,
                 '/contacts/<int:contact_id>/skills/<string:skill_id>',
                 '/contacts/<int:contact_id>/skills/<string:skill_id>/')
api.add_resource(resources.ContactCapabilities,
                 '/contacts/<int:contact_id>/capabilities/',
                 '/contacts/<int:contact_id>/capabilities/')
api.add_resource(resources.ContactCapabilitySuggestions,
                 '/contacts/<int:contact_id>/capabilities/<string:capability_id>/suggestion',
                 '/contacts/<int:contact_id>/capabilities/<string:capability_id>/suggestion/')
api.add_resource(resources.ContactCapabilitySuggestionOne,
                 '/contacts/<int:contact_id>/capabilities/<string:capability_id>/suggestion/<string:skill_id>',
                 '/contacts/<int:contact_id>/capabilities/<string:capability_id>/suggestion/<string:skill_id>/')
api.add_resource(resources.CapabilityRecommended,
                 '/capabilities',
                 '/capabilities/')
api.add_resource(resources.AutocompleteSkill,
                 '/skills/autocomplete',
                 '/skills/autocomplete/')
api.add_resource(resources.ExperienceAll,
                 '/contacts/<int:contact_id>/experiences/',
                 '/contacts/<int:contact_id>/experiences')
api.add_resource(resources.ExperienceOne,
                 '/experiences/<int:experience_id>',
                 '/experiences/<int:experience_id>/')
api.add_resource(resources.OpportunityAppOne,
                 '/contacts/<int:contact_id>/app/<string:opportunity_id>',
                 '/contacts/<int:contact_id>/app/<string:opportunity_id>/')
api.add_resource(resources.OpportunityAppSubmit,
                 '/contacts/<int:contact_id>/app/<string:opportunity_id>/submit',
                 '/contacts/<int:contact_id>/app/<string:opportunity_id>/submit/')
api.add_resource(resources.OpportunityAppReject,
                 '/contacts/<int:contact_id>/app/<string:opportunity_id>/not-a-fit',
                 '/contacts/<int:contact_id>/app/<string:opportunity_id>/not-a-fit/')
api.add_resource(resources.OpportunityAppInterview,
                 '/contacts/<int:contact_id>/app/<string:opportunity_id>/interview',
                 '/contacts/<int:contact_id>/app/<string:opportunity_id>/interview/')
api.add_resource(resources.OpportunityAppConsider,
                 '/contacts/<int:contact_id>/app/<string:opportunity_id>/consider',
                 '/contacts/<int:contact_id>/app/<string:opportunity_id>/consider/')
api.add_resource(resources.OpportunityAppAll,
                 '/contacts/<int:contact_id>/app',
                 '/contacts/<int:contact_id>/app/')
api.add_resource(resources.OpportunityAppRecommend,
                 '/contacts/<int:contact_id>/app/<string:opportunity_id>/recommend',
                 '/contacts/<int:contact_id>/app/<string:opportunity_id>/recommend/')
api.add_resource(resources.OpportunityAppReopen,
                 '/contacts/<int:contact_id>/app/<string:opportunity_id>/reopen',
                 '/contacts/<int:contact_id>/app/<string:opportunity_id>/reopen/')
api.add_resource(resources.Session,
                 '/session/',
                 '/session')
api.add_resource(resources.OpportunityAll,
                 '/opportunity',
                 '/opportunity/')
api.add_resource(resources.OpportunityAllInternal,
                 '/internal/opportunities/',
                 '/internal/opportunities')
api.add_resource(resources.OpportunityOne,
                 '/opportunity/<string:opportunity_id>',
                 '/opportunity/<string:opportunity_id>/')
api.add_resource(resources.OpportunityOneOrg,
                 '/org/opportunities/<string:opportunity_id>',
                 '/org/opportunities/<string:opportunity_id>/')
api.add_resource(resources.OpportunityDeactivate,
                 '/opportunity/<string:opportunity_id>/deactivate',
                 '/opportunity/<string:opportunity_id>/deactivate/')
api.add_resource(resources.OpportunityActivate,
                 '/opportunity/<string:opportunity_id>/activate',
                 '/opportunity/<string:opportunity_id>/activate/')
api.add_resource(resources.ProfileOne,
                 '/contacts/<int:contact_id>/about-me',
                 '/contacts/<int:contact_id>/about-me/')
api.add_resource(resources.ContactProgramAppsOne,
                 '/contacts/<int:contact_id>/program-apps',
                 '/contacts/<int:contact_id>/program-apps/')
api.add_resource(resources.ContactProgramAppsAll,
                 '/contacts/program-apps',
                 '/contacts/program-apps/')
api.add_resource(resources.ContactProgramAppsInterested,
                 '/contacts/<int:contact_id>/program-apps/interested',
                 '/contacts/<int:contact_id>/program-apps/interested/')
api.add_resource(resources.ContactInstructions,
                 '/contacts/<int:contact_id>/instructions',
                 '/contacts/<int:contact_id>/instructions/')
api.add_resource(resources.ProfileSubmit,
                 '/contacts/<int:contact_id>/submit',
                 '/contacts/<int:contact_id>/submit/',
                 '/contacts/<int:contact_id>/profile/submit',
                 '/contacts/<int:contact_id>/profile/submit/')
api.add_resource(resources.ProgramAll,
                 '/programs',
                 '/programs/')
api.add_resource(resources.ContactFull,
                 '/contacts/<int:contact_id>/profile',
                 '/contacts/<int:contact_id>/profile/')
api.add_resource(resources.Filter,
                 '/contacts/filter',
                 '/contacts/filter/')
