"""empty message

Revision ID: 04a40568b938
Revises: 4be84846d62e
Create Date: 2019-12-03 13:19:36.745522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04a40568b938'
down_revision = '4be84846d62e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experience', sa.Column('degree_other', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('experience', 'degree_other')
    # ### end Alembic commands ###
