"""Remove character limit exp

Revision ID: 18e0b71bbba7
Revises: 2846b92d3072
Create Date: 2020-04-10 10:35:00.600904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18e0b71bbba7'
down_revision = '2846b92d3072'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('experience', 'host',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String,
               existing_nullable=False)
    op.alter_column('experience', 'title',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String,
               existing_nullable=False)
    op.alter_column('experience', 'link',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String,
               existing_nullable=True)
    op.alter_column('experience', 'description',
               existing_type=sa.VARCHAR(length=2000),
               type_=sa.String,
               existing_nullable=True)
    op.alter_column('achievement', 'description',
               existing_type=sa.VARCHAR(length=2000),
               type_=sa.String,
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('experience', 'host',
               existing_type=sa.VARCHAR,
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('experience', 'title',
               existing_type=sa.VARCHAR,
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('experience', 'link',
               existing_type=sa.VARCHAR,
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('experience', 'description',
               existing_type=sa.VARCHAR,
               type_=sa.String(length=2000),
               existing_nullable=True)
    op.alter_column('achievement', 'description',
               existing_type=sa.VARCHAR,
               type_=sa.String(length=2000),
               existing_nullable=True)
    # ### end Alembic commands ###
