"""empty message

Revision ID: 1d466ee887b9
Revises: fb2ae36bd248
Create Date: 2019-10-22 12:56:18.708705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d466ee887b9'
down_revision = 'fb2ae36bd248'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experience', sa.Column('location', sa.String(length=255), nullable=True))
    op.drop_column('experience', 'location_city')
    op.drop_column('experience', 'location_state')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experience', sa.Column('location_state', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('experience', sa.Column('location_city', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('experience', 'location')
    # ### end Alembic commands ###
