"""rename to gdoc_id

Revision ID: 1edd5a5116c1
Revises: 4cae791dc15e
Create Date: 2020-02-17 12:55:05.410373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1edd5a5116c1'
down_revision = '4cae791dc15e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunity', sa.Column('gdoc_id', sa.String(length=200), nullable=False))
    op.drop_column('opportunity', 'gdoc_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunity', sa.Column('gdoc_link', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.drop_column('opportunity', 'gdoc_id')
    # ### end Alembic commands ###
