"""Adds is_active to opportunity

Revision ID: 2846b92d3072
Revises: 92aa4bd5401a
Create Date: 2020-04-06 14:22:18.327955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2846b92d3072'
down_revision = '92aa4bd5401a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunity', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.execute("UPDATE opportunity SET is_active = true")
    op.alter_column('opportunity_app', 'is_active',
               existing_type=sa.Boolean(),
               nullable=False)
    op.alter_column('opportunity', 'is_active',
               existing_type=sa.Boolean(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('opportunity', 'is_active')
    op.alter_column('opportunity_app', 'is_active',
               existing_type=sa.Boolean(),
               nullable=True)
    # ### end Alembic commands ###
