"""empty message

Revision ID: 2be793fbf577
Revises: 581464g1c63f
Create Date: 2020-01-28 13:39:51.299596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2be793fbf577'
down_revision = '581464g1c63f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('terms_agreement', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact', 'terms_agreement')
    # ### end Alembic commands ###
