"""DEV add programs_completed table and update profile table

Revision ID: 4a0bb4a548dc
Revises: 5ec1172a690f
Create Date: 2020-07-21 11:53:53.759495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a0bb4a548dc'
down_revision = '5ec1172a690f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('programs_completed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('fellowship', sa.Boolean(), nullable=True),
    sa.Column('mayoral_fellowship', sa.Boolean(), nullable=True),
    sa.Column('public_allies', sa.Boolean(), nullable=True),
    sa.Column('kiva', sa.Boolean(), nullable=True),
    sa.Column('civic_innovators', sa.Boolean(), nullable=True),
    sa.Column('elevation_awards', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('profile', sa.Column('hear_about_us', sa.String(), nullable=True))
    op.add_column('profile', sa.Column('hear_about_us_other', sa.String(), nullable=True))
    op.add_column('profile', sa.Column('needs_help_programs', sa.String(), nullable=True))
    op.add_column('profile', sa.Column('value_question1', sa.String(), nullable=True))
    op.add_column('profile', sa.Column('value_question2', sa.String(), nullable=True))
    op.add_column('program_app', sa.Column('decision_date', sa.Date(), nullable=True))
    op.drop_column('program_app', 'date_approved')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('program_app', sa.Column('date_approved', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('program_app', 'decision_date')
    op.drop_column('profile', 'value_question2')
    op.drop_column('profile', 'value_question1')
    op.drop_column('profile', 'needs_help_programs')
    op.drop_column('profile', 'hear_about_us_other')
    op.drop_column('profile', 'hear_about_us')
    op.drop_table('programs_completed')
    # ### end Alembic commands ###
