"""empty message

Revision ID: 4be84846d62e
Revises: a00f8e47031b
Create Date: 2019-11-25 13:41:40.624258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4be84846d62e'
down_revision = 'a00f8e47031b'
branch_labels = None
depends_on = None

degree = sa.Enum('high_school', 'associates', 'undergraduate', 'masters', 'doctoral', name='Degree')

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experience', sa.Column('link', sa.String(length=255), nullable=True))
    op.alter_column('experience', 'degree', type_=sa.String(length=100), existing_type=degree)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('experience', 'link')
    op.alter_column('experience', 'degree', type_=degree,
                    existing_type=sa.String(length=100), postgresql_using='degree::"Degree"')
    # ### end Alembic commands ###
