"""empty message

Revision ID: 51f4efa89e84
Revises: 2f9c7b6ac02b
Create Date: 2019-10-07 10:16:49.855200

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql



# revision identifiers, used by Alembic.
revision = '51f4efa89e84'
down_revision = '2f9c7b6ac02b'
branch_labels = None
depends_on = None

month = postgresql.ENUM('january', 'february', 'march', 'april', 'may', 'june',
                        'july', 'august', 'september', 'october', 'november',
                        'december', name='MonthType')


def upgrade():
    month.create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experience', sa.Column('end_month', month, nullable=True))
    op.add_column('experience', sa.Column('end_year', sa.Integer(), nullable=True))
    op.add_column('experience', sa.Column('location_city', sa.String(length=100), nullable=True))
    op.add_column('experience', sa.Column('location_state', sa.String(length=100), nullable=True))
    op.add_column('experience', sa.Column('start_month', month, nullable=True))
    op.add_column('experience', sa.Column('start_year', sa.Integer(), nullable=False))
    op.drop_constraint('experience_address_id_fkey', 'experience', type_='foreignkey')
    op.drop_column('experience', 'date_start')
    op.drop_column('experience', 'address_id')
    op.drop_column('experience', 'date_end')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experience', sa.Column('date_end', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('experience', sa.Column('address_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('experience', sa.Column('date_start', sa.DATE(), autoincrement=False, nullable=False))
    op.create_foreign_key('experience_address_id_fkey', 'experience', 'address', ['address_id'], ['id'])
    op.drop_column('experience', 'start_year')
    op.drop_column('experience', 'start_month')
    op.drop_column('experience', 'location_state')
    op.drop_column('experience', 'location_city')
    op.drop_column('experience', 'end_year')
    op.drop_column('experience', 'end_month')
    # ### end Alembic commands ###

    month.drop(op.get_bind())
