"""empty message

Revision ID: 560fa6a046d3
Revises: 3031dca64433
Create Date: 2019-11-13 13:08:46.767308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '560fa6a046d3'
down_revision = '3031dca64433'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('account_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact', 'account_id')
    # ### end Alembic commands ###
