"""Adds demographic fields to contact

Revision ID: 671364b9b36c
Revises: 0e4d2a73b476
Create Date: 2020-01-12 13:55:01.471575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '671364b9b36c'
down_revision = '0e4d2a73b476'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact', 'race_all')
    op.drop_column('contact', 'gender')
    op.add_column('contact', sa.Column('race_all', sa.String(length=255), nullable=True))
    op.add_column('contact', sa.Column('gender', sa.String(length=100), nullable=True))
    op.add_column('contact', sa.Column('gender_other', sa.String(length=255), nullable=True))
    op.add_column('contact', sa.Column('pronouns', sa.String(length=100), nullable=True))
    op.add_column('contact', sa.Column('pronouns_other', sa.String(length=255), nullable=True))
    op.add_column('contact', sa.Column('race_other', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact', 'race_all')
    op.drop_column('contact', 'gender')
    op.drop_column('contact', 'race_other')
    op.drop_column('contact', 'pronouns_other')
    op.drop_column('contact', 'pronouns')
    op.drop_column('contact', 'gender_other')
    op.add_column('contact', sa.Column('gender', sa.Enum('female', 'male', 'non_binary', name='Gender'), nullable=True)),
    op.add_column('contact', sa.Column('race_all', sa.Enum('asian', 'white', 'black', 'hispanic', name='Race'), nullable=True))
    # ### end Alembic commands ###
