"""DEV adds program_name to opportunity table

Revision ID: 7beedfdacaea
Revises: f64f9a9be2a4
Create Date: 2020-04-30 16:28:47.506865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7beedfdacaea'
down_revision = 'f64f9a9be2a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunity', sa.Column('program_name', sa.String(), nullable=True))
    op.execute("UPDATE opportunity SET program_name='Place for Purpose'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('opportunity', 'program_name')
    # ### end Alembic commands ###
