"""PROD adds card_id to contact table

Revision ID: 7e898d882b46
Revises: 582dc4d0b1ca
Create Date: 2020-08-17 15:55:04.418378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e898d882b46'
down_revision = '582dc4d0b1ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('card_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact', 'card_id')
    # ### end Alembic commands ###
