"""PROD adds race_all table to race table

Revision ID: 7f42a867a4a7
Revises: 7e898d882b46
Create Date: 2020-09-14 08:23:44.457249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f42a867a4a7'
down_revision = '7e898d882b46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('race', sa.Column('race_all', sa.String(), nullable=True))
    op.execute("""UPDATE race SET race_all = 'No Response'""")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('race', 'race_all')
    # ### end Alembic commands ###
