"""Adds review table

Revision ID: 8c6fb2534ac1
Revises: 581464g1c63f
Create Date: 2020-02-02 18:23:14.325906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c6fb2534ac1'
down_revision = '581464g1c63f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('stage', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('card_id', sa.String(length=25), nullable=True),
    sa.Column('program_contact_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['program_contact_id'], ['program_contact.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('cycle', sa.Column('review_talent_board_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cycle', 'review_talent_board_id')
    op.drop_table('review')
    # ### end Alembic commands ###
