"""Add opportunity tables

Revision ID: 8d25b12fb35b
Revises: 8c6fb2534ac1
Create Date: 2020-02-18 14:39:59.601055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d25b12fb35b'
down_revision = '8c6fb2534ac1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opportunity',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('short_description', sa.String(length=2000), nullable=False),
    sa.Column('gdoc_id', sa.String(length=200), nullable=False),
    sa.Column('card_id', sa.String(), nullable=False),
    sa.Column('stage', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opportunity_app',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.String(), nullable=False),
    sa.Column('interest_statement', sa.String(length=2000), nullable=True),
    sa.Column('stage', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], ),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('oppapp_contact_opportunity', 'opportunity_app', ['contact_id', 'opportunity_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('oppapp_contact_opportunity', table_name='opportunity_app')
    op.drop_table('opportunity_app')
    op.drop_table('opportunity')
    # ### end Alembic commands ###
