"""Creates resume_schema table

Revision ID: 907e98b9bd9d
Revises: b665baf49c4a
Create Date: 2020-02-26 11:34:35.104437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '907e98b9bd9d'
down_revision = 'b665baf49c4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resume', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('opportunity_app', sa.Column('resume_id', sa.Integer(), nullable=True))
    op.create_foreign_key('opportunity_resume_id_fkey', 'opportunity_app', 'resume_snapshot', ['resume_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('opportunity_resume_id_fkey', 'opportunity_app', type_='foreignkey')
    op.drop_column('opportunity_app', 'resume_id')
    op.drop_table('resume_snapshot')
    # ### end Alembic commands ###
