"""Adds interview_date and interview_time to opportunity_app table

Revision ID: 92aa4bd5401a
Revises: b6cec539eefd
Create Date: 2020-03-15 21:28:14.981402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92aa4bd5401a'
down_revision = 'b6cec539eefd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunity_app', sa.Column('interview_date', sa.Date(), nullable=True))
    op.add_column('opportunity_app', sa.Column('interview_time', sa.String(), nullable=True))
    op.execute('UPDATE opportunity_app SET is_active=true WHERE is_active IS NULL;')
    op.alter_column('opportunity_app', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('opportunity_app', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('opportunity_app', 'interview_time')
    op.drop_column('opportunity_app', 'interview_date')
    # ### end Alembic commands ###
