"""empty message

Revision ID: a00f8e47031b
Revises: 560fa6a046d3
Create Date: 2019-11-20 22:41:31.741529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a00f8e47031b'
down_revision = '560fa6a046d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skill_item',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], ),
    sa.PrimaryKeyConstraint('id', 'contact_id', name='skill_item_pk')
    )
    op.create_table('experience_skills',
    sa.Column('experience_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.String(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['experience_id'], ['experience.id'], ),
    sa.ForeignKeyConstraint(['skill_id', 'contact_id'], ['skill_item.id', 'skill_item.contact_id'], ),
    sa.PrimaryKeyConstraint('experience_id', 'skill_id', 'contact_id', name='experience_skills_pk')
    )
    op.create_index(op.f('ix_experience_skills_skill_id'), 'experience_skills', ['skill_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_experience_skills_skill_id'), table_name='experience_skills')
    op.drop_table('experience_skills')
    op.drop_table('skill_item')
    # ### end Alembic commands ###
