"""adds card_id and stage to opp table

Revision ID: a1620cf0afb5
Revises: 1edd5a5116c1
Create Date: 2020-02-17 18:08:34.483937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1620cf0afb5'
down_revision = '1edd5a5116c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunity', sa.Column('card_id', sa.String(), nullable=False))
    op.add_column('opportunity', sa.Column('stage', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('opportunity', 'stage')
    op.drop_column('opportunity', 'card_id')
    # ### end Alembic commands ###
