"""PROD add link_name to experience table

Revision ID: b4243d2f08a0
Revises: fd4b67491291
Create Date: 2020-04-27 14:36:39.711453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4243d2f08a0'
down_revision = 'fd4b67491291'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experience', sa.Column('link_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('experience', 'link_name')
    # ### end Alembic commands ###
