"""Add org_name, cycle_id, gdoc_link to opp table

Revision ID: b665baf49c4a
Revises: e30cb230b9f6
Create Date: 2020-02-24 14:56:21.572600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b665baf49c4a'
down_revision = 'e30cb230b9f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunity', sa.Column('cycle_id', sa.Integer(), nullable=False))
    op.add_column('opportunity', sa.Column('gdoc_link', sa.String(length=200), nullable=False))
    op.add_column('opportunity', sa.Column('org_name', sa.String(length=255), nullable=False))
    op.alter_column('opportunity', 'card_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('opportunity', 'gdoc_id',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.create_foreign_key('opportunity_cycle_id_fkey', 'opportunity', 'cycle', ['cycle_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('opportunity_cycle_id_fkey', 'opportunity', type_='foreignkey')
    op.alter_column('opportunity', 'gdoc_id',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('opportunity', 'card_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('opportunity', 'org_name')
    op.drop_column('opportunity', 'gdoc_link')
    op.drop_column('opportunity', 'cycle_id')
    # ### end Alembic commands ###
