"""Adds is_active to opportunity_app table

Revision ID: b6cec539eefd
Revises: f5429cf67f74
Create Date: 2020-03-01 19:03:37.579189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6cec539eefd'
down_revision = 'f5429cf67f74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunity_app', sa.Column('is_active', sa.Boolean()))
    op.execute("UPDATE opportunity_app SET is_active = true")
    op.alter_column('opportunity_app', 'is_active',
               existing_type=sa.Boolean(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('opportunity_app', 'is_active')
    # ### end Alembic commands ###
