"""DEV changes needs_program_help to boolean

Revision ID: bded2d30fef8
Revises: 4a0bb4a548dc
Create Date: 2020-07-29 11:46:18.677156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bded2d30fef8'
down_revision = '4a0bb4a548dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile', 'needs_help_programs')
    op.add_column('profile', sa.Column('needs_help_programs', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile', 'needs_help_programs')
    op.add_column('profile', sa.Column('needs_help_programs', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
