"""DEV adds race_all to race table

Revision ID: c943c888df2c
Revises: e78476a9f116
Create Date: 2020-09-10 12:23:27.988245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c943c888df2c'
down_revision = 'e78476a9f116'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('race', sa.Column('race_all', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('race', 'race_all')
    # ### end Alembic commands ###
