"""Adds is_active field to opportunity_app

Revision ID: d509c14239b4
Revises: 907e98b9bd9d
Create Date: 2020-03-02 14:02:18.080621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd509c14239b4'
down_revision = '907e98b9bd9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunity_app', sa.Column('is_active', sa.Boolean()))
    op.execute("UPDATE opportunity_app SET is_active = true")
    op.alter_column('opportunity_app', 'is_active',
               existing_type=sa.Boolean(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('opportunity_app', 'is_active')
    # ### end Alembic commands ###
