"""empty message

Revision ID: e1e5db6b0a33
Revises: 581464g1c63f
Create Date: 2020-01-21 17:13:26.598278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1e5db6b0a33'
down_revision = '581464g1c63f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_session',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('auth_id', sa.String(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('jwt', sa.String(length=1000), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_session')
    # ### end Alembic commands ###
