"""adds gdoc_link to opportunity table

Revision ID: e3926f7bbb14
Revises: eb6d9410ef2a
Create Date: 2020-02-24 13:15:04.334109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3926f7bbb14'
down_revision = 'eb6d9410ef2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunity', sa.Column('gdoc_link', sa.String(length=200)))
    op.alter_column('opportunity', 'card_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('opportunity', 'cycle_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('opportunity', 'gdoc_id',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.execute("UPDATE opportunity SET gdoc_link = 'https://docs.google.com/document/d/1eVY9Zx1hYQnpOKF6okLTuSsHL3eMZ4qV9oSal3NXIgo/edit'")
    op.alter_column('opportunity', 'gdoc_link',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('opportunity', 'gdoc_id',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('opportunity', 'cycle_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('opportunity', 'card_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('opportunity', 'gdoc_link')
    # ### end Alembic commands ###
