"""DEV adds card_id to contact table

Revision ID: e78476a9f116
Revises: bded2d30fef8
Create Date: 2020-08-06 18:19:25.311600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e78476a9f116'
down_revision = 'bded2d30fef8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('card_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact', 'card_id')
    # ### end Alembic commands ###
