"""Adds is_active to opportunity

Revision ID: e86111bfd274
Revises: ef595b4c8fb9
Create Date: 2020-04-07 14:41:29.499982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e86111bfd274'
down_revision = 'ef595b4c8fb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunity', sa.Column('is_active', sa.Boolean()))
    op.execute("UPDATE opportunity SET is_active = true")
    op.alter_column('opportunity', 'is_active',
               existing_type=sa.Boolean(),
               nullable=False)
    op.alter_column('opportunity_app', 'is_active',
               existing_type=sa.Boolean(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('opportunity', 'is_active')
    op.alter_column('opportunity_app', 'is_active',
               existing_type=sa.Boolean(),
               nullable=True)
    # ### end Alembic commands ###
