"""empty message

Revision ID: f115c8443af6
Revises: fd4b67491291
Create Date: 2020-04-24 14:29:08.586970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f115c8443af6'
down_revision = 'fd4b67491291'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experience', sa.Column('link_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('experience', 'link_name')
    # ### end Alembic commands ###
