"""Adds resume_snapshot table

Revision ID: f5429cf67f74
Revises: e3926f7bbb14
Create Date: 2020-02-25 12:36:26.494235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5429cf67f74'
down_revision = 'e3926f7bbb14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resume', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('opportunity', 'gdoc_link',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.add_column('opportunity_app', sa.Column('resume_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'opportunity_app', 'resume_snapshot', ['resume_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'opportunity_app', type_='foreignkey')
    op.drop_column('opportunity_app', 'resume_id')
    op.alter_column('opportunity', 'gdoc_link',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.drop_table('resume_snapshot')
    # ### end Alembic commands ###
