"""DEV removes cycle, review, question, response tables

Revision ID: f57f02a95449
Revises: 70546a856cab
Create Date: 2020-07-07 15:11:21.433086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f57f02a95449'
down_revision = '70546a856cab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('opportunity_cycle_id_fkey', 'opportunity', type_='foreignkey')
    op.drop_table('cycle')
    op.drop_table('review')
    op.drop_table('response')
    op.drop_table('question')
    op.add_column('opportunity', sa.Column('program_id', sa.Integer()))
    op.execute("""INSERT INTO program (name) VALUES ('Mayoral Fellowship')""")
    op.execute("""INSERT INTO program (name) VALUES ('Fellowship')""")
    op.execute("""UPDATE opportunity SET program_id = 1""")
    op.execute("""UPDATE opportunity SET program_id = 2
               WHERE program_name = 'Mayoral Fellowship'""")
    op.execute("""UPDATE opportunity SET program_id = 3
               WHERE program_name = 'Fellowship'""")
    op.alter_column('opportunity', 'program_id', existing_type=sa.Integer(), nullable=False)
    op.create_foreign_key('opportunity_program_id_fkey', 'opportunity', 'program', ['program_id'], ['id'])
    op.drop_column('opportunity', 'cycle_id')
    op.add_column('program', sa.Column('trello_board_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('program', 'trello_board_id')
    op.drop_constraint('opportunity_program_id_fkey', 'opportunity', type_='foreignkey')
    op.drop_column('opportunity', 'program_id')
    op.create_table('response',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('program_contact_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('response_text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['program_contact_id'], ['program_contact.id'], name='response_program_contact_id_fkey'),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], name='response_question_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='response_pkey')
    )
    op.create_table('review',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('stage', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('card_id', sa.VARCHAR(length=25), autoincrement=False, nullable=True),
    sa.Column('program_contact_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['program_contact_id'], ['program_contact.id'], name='review_program_contact_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='review_pkey')
    )
    op.create_table('question',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('program_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('question_text', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('limit_word', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('limit_character', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['program.id'], name='question_program_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='question_pkey')
    )
    op.create_table('cycle',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('program_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date_start', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('date_end', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('intake_talent_board_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('intake_org_board_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('match_talent_board_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('match_opp_board_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('review_talent_board_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='cycle_pkey')
    )

    op.add_column('opportunity', sa.Column('cycle_id', sa.INTEGER(), autoincrement=False))
    op.execute("""UPDATE opportunity SET cycle_id = 1""")
    op.alter_column('opportunity', 'cycle_id', existing_type=sa.Integer(), nullable=False)
    op.create_foreign_key('opportunity_cycle_id_fkey', 'opportunity', 'cycle', ['cycle_id'], ['id'])
    # ### end Alembic commands ###
