"""DEV add link_name to experience

Revision ID: f64f9a9be2a4
Revises: 18e0b71bbba7
Create Date: 2020-04-24 15:18:15.846739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f64f9a9be2a4'
down_revision = '18e0b71bbba7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experience', sa.Column('link_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('experience', 'link_name')
    # ### end Alembic commands ###
