"""Add org_name to opportunity

Revision ID: fec0987cfc79
Revises: aec34eccaa79
Create Date: 2020-02-17 21:49:52.195826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fec0987cfc79'
down_revision = 'aec34eccaa79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunity', sa.Column('org_name', sa.String(length=255)))
    op.execute("UPDATE opportunity SET org_name = 'Test Org'")
    op.alter_column('opportunity', 'org_name', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('opportunity', 'org_name')
    # ### end Alembic commands ###
